<?php

/**
 * @file
 * This file demonstrates hwo to use hook functions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function rsvplist_theme() {
  return [
    'simple_text_field' => [
      'variables' => ['value' => NULL],
    ],
    'simple_text_field_minimal' => [
      'variables' => ['value' => NULL],
    ],
    'hello_block' => [
      'variables' => [
        'custom_data' => [],
        'custom_string' => '',
      ],
    ],
    'hello_block2' => [
      'variables' => [
        'active_tab' => NULL,
        'body_text' => NULL,
        'tabs' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_node_form_alter()
 */
function rsvplist_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('rsvplist.form_alter')->alterNodeForm($form, $form_state);
}

