<?php

/**
 * @file
 * This file demonstrates hwo to use hook functions.
 */

/**
 * Implements hook_cron().
 */
function mymodule_cron() {
  \Drupal::messenger()->addMessage(t("Hello from my module!"));
}

/**
 * Implements hook_form_alter().
 */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {

  // \Drupal::messenger()->addMessage($form_id);
  if($form_id == 'node_article_form'){
    $form['actions']['submit']['#value'] = t('Save this awesome article!!!!!!!!!!!!!!!!!!!!');
  }
}
